/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ModernIndexRouteImport } from './routes/modern/index'
import { Route as CompleteFleetIndexRouteImport } from './routes/complete-fleet/index'
import { Route as ClassicIndexRouteImport } from './routes/classic/index'
import { Route as ServicesWeddingsRouteImport } from './routes/services/weddings'
import { Route as ServicesToursRouteImport } from './routes/services/tours'
import { Route as ServicesOneWayRouteImport } from './routes/services/one-way'
import { Route as ServicesExclusiveRouteImport } from './routes/services/exclusive'
import { Route as ServicesBusinessRouteImport } from './routes/services/business'
import { Route as ServicesAirportsRouteImport } from './routes/services/airports'
import { Route as ModernMercedesS500BrabusRouteImport } from './routes/modern/mercedes-s500-brabus'
import { Route as ModernMercedesMaybachRouteImport } from './routes/modern/mercedes-maybach'
import { Route as ModernBentleyMulsanneRouteImport } from './routes/modern/bentley-mulsanne'
import { Route as ModernBentleyFlyingSpurRouteImport } from './routes/modern/bentley-flying-spur'
import { Route as ClassicRollsRoyceSilverShadowRouteImport } from './routes/classic/rolls-royce-silver-shadow'
import { Route as ClassicRollsRoyceSilverCloudIiRouteImport } from './routes/classic/rolls-royce-silver-cloud-ii'
import { Route as ClassicOldsmobileSuper88RouteImport } from './routes/classic/oldsmobile-super-88'
import { Route as ClassicMercedes280slPagodaRouteImport } from './routes/classic/mercedes-280sl-pagoda'
import { Route as BookingWeddingRouteImport } from './routes/booking/wedding'
import { Route as BookingToursRouteImport } from './routes/booking/tours'
import { Route as BookingPaymentSuccessRouteImport } from './routes/booking/payment-success'
import { Route as BookingPaymentCancelRouteImport } from './routes/booking/payment-cancel'
import { Route as BookingOneWayRouteImport } from './routes/booking/one-way'
import { Route as BookingCorporateRouteImport } from './routes/booking/corporate'
import { Route as BookingAirportRouteImport } from './routes/booking/airport'
import { Route as BookingIdRouteImport } from './routes/booking/$id'
import { ServerRoute as ApiWeddingBookingServerRouteImport } from './routes/api/wedding-booking'
import { ServerRoute as ApiTourBookingServerRouteImport } from './routes/api/tour-booking'
import { ServerRoute as ApiContactServerRouteImport } from './routes/api/contact'
import { ServerRoute as ApiPaymentsStatusServerRouteImport } from './routes/api/payments/status'
import { ServerRoute as ApiPaymentsCreateCheckoutSessionServerRouteImport } from './routes/api/payments/create-checkout-session'

const rootServerRouteImport = createServerRootRoute()

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModernIndexRoute = ModernIndexRouteImport.update({
  id: '/modern/',
  path: '/modern/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteFleetIndexRoute = CompleteFleetIndexRouteImport.update({
  id: '/complete-fleet/',
  path: '/complete-fleet/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassicIndexRoute = ClassicIndexRouteImport.update({
  id: '/classic/',
  path: '/classic/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWeddingsRoute = ServicesWeddingsRouteImport.update({
  id: '/services/weddings',
  path: '/services/weddings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesToursRoute = ServicesToursRouteImport.update({
  id: '/services/tours',
  path: '/services/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesOneWayRoute = ServicesOneWayRouteImport.update({
  id: '/services/one-way',
  path: '/services/one-way',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesExclusiveRoute = ServicesExclusiveRouteImport.update({
  id: '/services/exclusive',
  path: '/services/exclusive',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBusinessRoute = ServicesBusinessRouteImport.update({
  id: '/services/business',
  path: '/services/business',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAirportsRoute = ServicesAirportsRouteImport.update({
  id: '/services/airports',
  path: '/services/airports',
  getParentRoute: () => rootRouteImport,
} as any)
const ModernMercedesS500BrabusRoute =
  ModernMercedesS500BrabusRouteImport.update({
    id: '/modern/mercedes-s500-brabus',
    path: '/modern/mercedes-s500-brabus',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModernMercedesMaybachRoute = ModernMercedesMaybachRouteImport.update({
  id: '/modern/mercedes-maybach',
  path: '/modern/mercedes-maybach',
  getParentRoute: () => rootRouteImport,
} as any)
const ModernBentleyMulsanneRoute = ModernBentleyMulsanneRouteImport.update({
  id: '/modern/bentley-mulsanne',
  path: '/modern/bentley-mulsanne',
  getParentRoute: () => rootRouteImport,
} as any)
const ModernBentleyFlyingSpurRoute = ModernBentleyFlyingSpurRouteImport.update({
  id: '/modern/bentley-flying-spur',
  path: '/modern/bentley-flying-spur',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassicRollsRoyceSilverShadowRoute =
  ClassicRollsRoyceSilverShadowRouteImport.update({
    id: '/classic/rolls-royce-silver-shadow',
    path: '/classic/rolls-royce-silver-shadow',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClassicRollsRoyceSilverCloudIiRoute =
  ClassicRollsRoyceSilverCloudIiRouteImport.update({
    id: '/classic/rolls-royce-silver-cloud-ii',
    path: '/classic/rolls-royce-silver-cloud-ii',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClassicOldsmobileSuper88Route =
  ClassicOldsmobileSuper88RouteImport.update({
    id: '/classic/oldsmobile-super-88',
    path: '/classic/oldsmobile-super-88',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClassicMercedes280slPagodaRoute =
  ClassicMercedes280slPagodaRouteImport.update({
    id: '/classic/mercedes-280sl-pagoda',
    path: '/classic/mercedes-280sl-pagoda',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookingWeddingRoute = BookingWeddingRouteImport.update({
  id: '/booking/wedding',
  path: '/booking/wedding',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingToursRoute = BookingToursRouteImport.update({
  id: '/booking/tours',
  path: '/booking/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingPaymentSuccessRoute = BookingPaymentSuccessRouteImport.update({
  id: '/booking/payment-success',
  path: '/booking/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingPaymentCancelRoute = BookingPaymentCancelRouteImport.update({
  id: '/booking/payment-cancel',
  path: '/booking/payment-cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingOneWayRoute = BookingOneWayRouteImport.update({
  id: '/booking/one-way',
  path: '/booking/one-way',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingCorporateRoute = BookingCorporateRouteImport.update({
  id: '/booking/corporate',
  path: '/booking/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingAirportRoute = BookingAirportRouteImport.update({
  id: '/booking/airport',
  path: '/booking/airport',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdRoute = BookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeddingBookingServerRoute = ApiWeddingBookingServerRouteImport.update({
  id: '/api/wedding-booking',
  path: '/api/wedding-booking',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiTourBookingServerRoute = ApiTourBookingServerRouteImport.update({
  id: '/api/tour-booking',
  path: '/api/tour-booking',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiContactServerRoute = ApiContactServerRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiPaymentsStatusServerRoute = ApiPaymentsStatusServerRouteImport.update({
  id: '/api/payments/status',
  path: '/api/payments/status',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiPaymentsCreateCheckoutSessionServerRoute =
  ApiPaymentsCreateCheckoutSessionServerRouteImport.update({
    id: '/api/payments/create-checkout-session',
    path: '/api/payments/create-checkout-session',
    getParentRoute: () => rootServerRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/booking/$id': typeof BookingIdRoute
  '/booking/airport': typeof BookingAirportRoute
  '/booking/corporate': typeof BookingCorporateRoute
  '/booking/one-way': typeof BookingOneWayRoute
  '/booking/payment-cancel': typeof BookingPaymentCancelRoute
  '/booking/payment-success': typeof BookingPaymentSuccessRoute
  '/booking/tours': typeof BookingToursRoute
  '/booking/wedding': typeof BookingWeddingRoute
  '/classic/mercedes-280sl-pagoda': typeof ClassicMercedes280slPagodaRoute
  '/classic/oldsmobile-super-88': typeof ClassicOldsmobileSuper88Route
  '/classic/rolls-royce-silver-cloud-ii': typeof ClassicRollsRoyceSilverCloudIiRoute
  '/classic/rolls-royce-silver-shadow': typeof ClassicRollsRoyceSilverShadowRoute
  '/modern/bentley-flying-spur': typeof ModernBentleyFlyingSpurRoute
  '/modern/bentley-mulsanne': typeof ModernBentleyMulsanneRoute
  '/modern/mercedes-maybach': typeof ModernMercedesMaybachRoute
  '/modern/mercedes-s500-brabus': typeof ModernMercedesS500BrabusRoute
  '/services/airports': typeof ServicesAirportsRoute
  '/services/business': typeof ServicesBusinessRoute
  '/services/exclusive': typeof ServicesExclusiveRoute
  '/services/one-way': typeof ServicesOneWayRoute
  '/services/tours': typeof ServicesToursRoute
  '/services/weddings': typeof ServicesWeddingsRoute
  '/classic': typeof ClassicIndexRoute
  '/complete-fleet': typeof CompleteFleetIndexRoute
  '/modern': typeof ModernIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/booking/$id': typeof BookingIdRoute
  '/booking/airport': typeof BookingAirportRoute
  '/booking/corporate': typeof BookingCorporateRoute
  '/booking/one-way': typeof BookingOneWayRoute
  '/booking/payment-cancel': typeof BookingPaymentCancelRoute
  '/booking/payment-success': typeof BookingPaymentSuccessRoute
  '/booking/tours': typeof BookingToursRoute
  '/booking/wedding': typeof BookingWeddingRoute
  '/classic/mercedes-280sl-pagoda': typeof ClassicMercedes280slPagodaRoute
  '/classic/oldsmobile-super-88': typeof ClassicOldsmobileSuper88Route
  '/classic/rolls-royce-silver-cloud-ii': typeof ClassicRollsRoyceSilverCloudIiRoute
  '/classic/rolls-royce-silver-shadow': typeof ClassicRollsRoyceSilverShadowRoute
  '/modern/bentley-flying-spur': typeof ModernBentleyFlyingSpurRoute
  '/modern/bentley-mulsanne': typeof ModernBentleyMulsanneRoute
  '/modern/mercedes-maybach': typeof ModernMercedesMaybachRoute
  '/modern/mercedes-s500-brabus': typeof ModernMercedesS500BrabusRoute
  '/services/airports': typeof ServicesAirportsRoute
  '/services/business': typeof ServicesBusinessRoute
  '/services/exclusive': typeof ServicesExclusiveRoute
  '/services/one-way': typeof ServicesOneWayRoute
  '/services/tours': typeof ServicesToursRoute
  '/services/weddings': typeof ServicesWeddingsRoute
  '/classic': typeof ClassicIndexRoute
  '/complete-fleet': typeof CompleteFleetIndexRoute
  '/modern': typeof ModernIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/booking/$id': typeof BookingIdRoute
  '/booking/airport': typeof BookingAirportRoute
  '/booking/corporate': typeof BookingCorporateRoute
  '/booking/one-way': typeof BookingOneWayRoute
  '/booking/payment-cancel': typeof BookingPaymentCancelRoute
  '/booking/payment-success': typeof BookingPaymentSuccessRoute
  '/booking/tours': typeof BookingToursRoute
  '/booking/wedding': typeof BookingWeddingRoute
  '/classic/mercedes-280sl-pagoda': typeof ClassicMercedes280slPagodaRoute
  '/classic/oldsmobile-super-88': typeof ClassicOldsmobileSuper88Route
  '/classic/rolls-royce-silver-cloud-ii': typeof ClassicRollsRoyceSilverCloudIiRoute
  '/classic/rolls-royce-silver-shadow': typeof ClassicRollsRoyceSilverShadowRoute
  '/modern/bentley-flying-spur': typeof ModernBentleyFlyingSpurRoute
  '/modern/bentley-mulsanne': typeof ModernBentleyMulsanneRoute
  '/modern/mercedes-maybach': typeof ModernMercedesMaybachRoute
  '/modern/mercedes-s500-brabus': typeof ModernMercedesS500BrabusRoute
  '/services/airports': typeof ServicesAirportsRoute
  '/services/business': typeof ServicesBusinessRoute
  '/services/exclusive': typeof ServicesExclusiveRoute
  '/services/one-way': typeof ServicesOneWayRoute
  '/services/tours': typeof ServicesToursRoute
  '/services/weddings': typeof ServicesWeddingsRoute
  '/classic/': typeof ClassicIndexRoute
  '/complete-fleet/': typeof CompleteFleetIndexRoute
  '/modern/': typeof ModernIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/booking/$id'
    | '/booking/airport'
    | '/booking/corporate'
    | '/booking/one-way'
    | '/booking/payment-cancel'
    | '/booking/payment-success'
    | '/booking/tours'
    | '/booking/wedding'
    | '/classic/mercedes-280sl-pagoda'
    | '/classic/oldsmobile-super-88'
    | '/classic/rolls-royce-silver-cloud-ii'
    | '/classic/rolls-royce-silver-shadow'
    | '/modern/bentley-flying-spur'
    | '/modern/bentley-mulsanne'
    | '/modern/mercedes-maybach'
    | '/modern/mercedes-s500-brabus'
    | '/services/airports'
    | '/services/business'
    | '/services/exclusive'
    | '/services/one-way'
    | '/services/tours'
    | '/services/weddings'
    | '/classic'
    | '/complete-fleet'
    | '/modern'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/booking/$id'
    | '/booking/airport'
    | '/booking/corporate'
    | '/booking/one-way'
    | '/booking/payment-cancel'
    | '/booking/payment-success'
    | '/booking/tours'
    | '/booking/wedding'
    | '/classic/mercedes-280sl-pagoda'
    | '/classic/oldsmobile-super-88'
    | '/classic/rolls-royce-silver-cloud-ii'
    | '/classic/rolls-royce-silver-shadow'
    | '/modern/bentley-flying-spur'
    | '/modern/bentley-mulsanne'
    | '/modern/mercedes-maybach'
    | '/modern/mercedes-s500-brabus'
    | '/services/airports'
    | '/services/business'
    | '/services/exclusive'
    | '/services/one-way'
    | '/services/tours'
    | '/services/weddings'
    | '/classic'
    | '/complete-fleet'
    | '/modern'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/booking/$id'
    | '/booking/airport'
    | '/booking/corporate'
    | '/booking/one-way'
    | '/booking/payment-cancel'
    | '/booking/payment-success'
    | '/booking/tours'
    | '/booking/wedding'
    | '/classic/mercedes-280sl-pagoda'
    | '/classic/oldsmobile-super-88'
    | '/classic/rolls-royce-silver-cloud-ii'
    | '/classic/rolls-royce-silver-shadow'
    | '/modern/bentley-flying-spur'
    | '/modern/bentley-mulsanne'
    | '/modern/mercedes-maybach'
    | '/modern/mercedes-s500-brabus'
    | '/services/airports'
    | '/services/business'
    | '/services/exclusive'
    | '/services/one-way'
    | '/services/tours'
    | '/services/weddings'
    | '/classic/'
    | '/complete-fleet/'
    | '/modern/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  BookingIdRoute: typeof BookingIdRoute
  BookingAirportRoute: typeof BookingAirportRoute
  BookingCorporateRoute: typeof BookingCorporateRoute
  BookingOneWayRoute: typeof BookingOneWayRoute
  BookingPaymentCancelRoute: typeof BookingPaymentCancelRoute
  BookingPaymentSuccessRoute: typeof BookingPaymentSuccessRoute
  BookingToursRoute: typeof BookingToursRoute
  BookingWeddingRoute: typeof BookingWeddingRoute
  ClassicMercedes280slPagodaRoute: typeof ClassicMercedes280slPagodaRoute
  ClassicOldsmobileSuper88Route: typeof ClassicOldsmobileSuper88Route
  ClassicRollsRoyceSilverCloudIiRoute: typeof ClassicRollsRoyceSilverCloudIiRoute
  ClassicRollsRoyceSilverShadowRoute: typeof ClassicRollsRoyceSilverShadowRoute
  ModernBentleyFlyingSpurRoute: typeof ModernBentleyFlyingSpurRoute
  ModernBentleyMulsanneRoute: typeof ModernBentleyMulsanneRoute
  ModernMercedesMaybachRoute: typeof ModernMercedesMaybachRoute
  ModernMercedesS500BrabusRoute: typeof ModernMercedesS500BrabusRoute
  ServicesAirportsRoute: typeof ServicesAirportsRoute
  ServicesBusinessRoute: typeof ServicesBusinessRoute
  ServicesExclusiveRoute: typeof ServicesExclusiveRoute
  ServicesOneWayRoute: typeof ServicesOneWayRoute
  ServicesToursRoute: typeof ServicesToursRoute
  ServicesWeddingsRoute: typeof ServicesWeddingsRoute
  ClassicIndexRoute: typeof ClassicIndexRoute
  CompleteFleetIndexRoute: typeof CompleteFleetIndexRoute
  ModernIndexRoute: typeof ModernIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/contact': typeof ApiContactServerRoute
  '/api/tour-booking': typeof ApiTourBookingServerRoute
  '/api/wedding-booking': typeof ApiWeddingBookingServerRoute
  '/api/payments/create-checkout-session': typeof ApiPaymentsCreateCheckoutSessionServerRoute
  '/api/payments/status': typeof ApiPaymentsStatusServerRoute
}
export interface FileServerRoutesByTo {
  '/api/contact': typeof ApiContactServerRoute
  '/api/tour-booking': typeof ApiTourBookingServerRoute
  '/api/wedding-booking': typeof ApiWeddingBookingServerRoute
  '/api/payments/create-checkout-session': typeof ApiPaymentsCreateCheckoutSessionServerRoute
  '/api/payments/status': typeof ApiPaymentsStatusServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/contact': typeof ApiContactServerRoute
  '/api/tour-booking': typeof ApiTourBookingServerRoute
  '/api/wedding-booking': typeof ApiWeddingBookingServerRoute
  '/api/payments/create-checkout-session': typeof ApiPaymentsCreateCheckoutSessionServerRoute
  '/api/payments/status': typeof ApiPaymentsStatusServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/api/contact'
    | '/api/tour-booking'
    | '/api/wedding-booking'
    | '/api/payments/create-checkout-session'
    | '/api/payments/status'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/api/contact'
    | '/api/tour-booking'
    | '/api/wedding-booking'
    | '/api/payments/create-checkout-session'
    | '/api/payments/status'
  id:
    | '__root__'
    | '/api/contact'
    | '/api/tour-booking'
    | '/api/wedding-booking'
    | '/api/payments/create-checkout-session'
    | '/api/payments/status'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiContactServerRoute: typeof ApiContactServerRoute
  ApiTourBookingServerRoute: typeof ApiTourBookingServerRoute
  ApiWeddingBookingServerRoute: typeof ApiWeddingBookingServerRoute
  ApiPaymentsCreateCheckoutSessionServerRoute: typeof ApiPaymentsCreateCheckoutSessionServerRoute
  ApiPaymentsStatusServerRoute: typeof ApiPaymentsStatusServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modern/': {
      id: '/modern/'
      path: '/modern'
      fullPath: '/modern'
      preLoaderRoute: typeof ModernIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-fleet/': {
      id: '/complete-fleet/'
      path: '/complete-fleet'
      fullPath: '/complete-fleet'
      preLoaderRoute: typeof CompleteFleetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic/': {
      id: '/classic/'
      path: '/classic'
      fullPath: '/classic'
      preLoaderRoute: typeof ClassicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/weddings': {
      id: '/services/weddings'
      path: '/services/weddings'
      fullPath: '/services/weddings'
      preLoaderRoute: typeof ServicesWeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/tours': {
      id: '/services/tours'
      path: '/services/tours'
      fullPath: '/services/tours'
      preLoaderRoute: typeof ServicesToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/one-way': {
      id: '/services/one-way'
      path: '/services/one-way'
      fullPath: '/services/one-way'
      preLoaderRoute: typeof ServicesOneWayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/exclusive': {
      id: '/services/exclusive'
      path: '/services/exclusive'
      fullPath: '/services/exclusive'
      preLoaderRoute: typeof ServicesExclusiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/business': {
      id: '/services/business'
      path: '/services/business'
      fullPath: '/services/business'
      preLoaderRoute: typeof ServicesBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/airports': {
      id: '/services/airports'
      path: '/services/airports'
      fullPath: '/services/airports'
      preLoaderRoute: typeof ServicesAirportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modern/mercedes-s500-brabus': {
      id: '/modern/mercedes-s500-brabus'
      path: '/modern/mercedes-s500-brabus'
      fullPath: '/modern/mercedes-s500-brabus'
      preLoaderRoute: typeof ModernMercedesS500BrabusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modern/mercedes-maybach': {
      id: '/modern/mercedes-maybach'
      path: '/modern/mercedes-maybach'
      fullPath: '/modern/mercedes-maybach'
      preLoaderRoute: typeof ModernMercedesMaybachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modern/bentley-mulsanne': {
      id: '/modern/bentley-mulsanne'
      path: '/modern/bentley-mulsanne'
      fullPath: '/modern/bentley-mulsanne'
      preLoaderRoute: typeof ModernBentleyMulsanneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modern/bentley-flying-spur': {
      id: '/modern/bentley-flying-spur'
      path: '/modern/bentley-flying-spur'
      fullPath: '/modern/bentley-flying-spur'
      preLoaderRoute: typeof ModernBentleyFlyingSpurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic/rolls-royce-silver-shadow': {
      id: '/classic/rolls-royce-silver-shadow'
      path: '/classic/rolls-royce-silver-shadow'
      fullPath: '/classic/rolls-royce-silver-shadow'
      preLoaderRoute: typeof ClassicRollsRoyceSilverShadowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic/rolls-royce-silver-cloud-ii': {
      id: '/classic/rolls-royce-silver-cloud-ii'
      path: '/classic/rolls-royce-silver-cloud-ii'
      fullPath: '/classic/rolls-royce-silver-cloud-ii'
      preLoaderRoute: typeof ClassicRollsRoyceSilverCloudIiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic/oldsmobile-super-88': {
      id: '/classic/oldsmobile-super-88'
      path: '/classic/oldsmobile-super-88'
      fullPath: '/classic/oldsmobile-super-88'
      preLoaderRoute: typeof ClassicOldsmobileSuper88RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic/mercedes-280sl-pagoda': {
      id: '/classic/mercedes-280sl-pagoda'
      path: '/classic/mercedes-280sl-pagoda'
      fullPath: '/classic/mercedes-280sl-pagoda'
      preLoaderRoute: typeof ClassicMercedes280slPagodaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/wedding': {
      id: '/booking/wedding'
      path: '/booking/wedding'
      fullPath: '/booking/wedding'
      preLoaderRoute: typeof BookingWeddingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/tours': {
      id: '/booking/tours'
      path: '/booking/tours'
      fullPath: '/booking/tours'
      preLoaderRoute: typeof BookingToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/payment-success': {
      id: '/booking/payment-success'
      path: '/booking/payment-success'
      fullPath: '/booking/payment-success'
      preLoaderRoute: typeof BookingPaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/payment-cancel': {
      id: '/booking/payment-cancel'
      path: '/booking/payment-cancel'
      fullPath: '/booking/payment-cancel'
      preLoaderRoute: typeof BookingPaymentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/one-way': {
      id: '/booking/one-way'
      path: '/booking/one-way'
      fullPath: '/booking/one-way'
      preLoaderRoute: typeof BookingOneWayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/corporate': {
      id: '/booking/corporate'
      path: '/booking/corporate'
      fullPath: '/booking/corporate'
      preLoaderRoute: typeof BookingCorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/airport': {
      id: '/booking/airport'
      path: '/booking/airport'
      fullPath: '/booking/airport'
      preLoaderRoute: typeof BookingAirportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id': {
      id: '/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof BookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/wedding-booking': {
      id: '/api/wedding-booking'
      path: '/api/wedding-booking'
      fullPath: '/api/wedding-booking'
      preLoaderRoute: typeof ApiWeddingBookingServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/tour-booking': {
      id: '/api/tour-booking'
      path: '/api/tour-booking'
      fullPath: '/api/tour-booking'
      preLoaderRoute: typeof ApiTourBookingServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/payments/status': {
      id: '/api/payments/status'
      path: '/api/payments/status'
      fullPath: '/api/payments/status'
      preLoaderRoute: typeof ApiPaymentsStatusServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/payments/create-checkout-session': {
      id: '/api/payments/create-checkout-session'
      path: '/api/payments/create-checkout-session'
      fullPath: '/api/payments/create-checkout-session'
      preLoaderRoute: typeof ApiPaymentsCreateCheckoutSessionServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  BookingIdRoute: BookingIdRoute,
  BookingAirportRoute: BookingAirportRoute,
  BookingCorporateRoute: BookingCorporateRoute,
  BookingOneWayRoute: BookingOneWayRoute,
  BookingPaymentCancelRoute: BookingPaymentCancelRoute,
  BookingPaymentSuccessRoute: BookingPaymentSuccessRoute,
  BookingToursRoute: BookingToursRoute,
  BookingWeddingRoute: BookingWeddingRoute,
  ClassicMercedes280slPagodaRoute: ClassicMercedes280slPagodaRoute,
  ClassicOldsmobileSuper88Route: ClassicOldsmobileSuper88Route,
  ClassicRollsRoyceSilverCloudIiRoute: ClassicRollsRoyceSilverCloudIiRoute,
  ClassicRollsRoyceSilverShadowRoute: ClassicRollsRoyceSilverShadowRoute,
  ModernBentleyFlyingSpurRoute: ModernBentleyFlyingSpurRoute,
  ModernBentleyMulsanneRoute: ModernBentleyMulsanneRoute,
  ModernMercedesMaybachRoute: ModernMercedesMaybachRoute,
  ModernMercedesS500BrabusRoute: ModernMercedesS500BrabusRoute,
  ServicesAirportsRoute: ServicesAirportsRoute,
  ServicesBusinessRoute: ServicesBusinessRoute,
  ServicesExclusiveRoute: ServicesExclusiveRoute,
  ServicesOneWayRoute: ServicesOneWayRoute,
  ServicesToursRoute: ServicesToursRoute,
  ServicesWeddingsRoute: ServicesWeddingsRoute,
  ClassicIndexRoute: ClassicIndexRoute,
  CompleteFleetIndexRoute: CompleteFleetIndexRoute,
  ModernIndexRoute: ModernIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiContactServerRoute: ApiContactServerRoute,
  ApiTourBookingServerRoute: ApiTourBookingServerRoute,
  ApiWeddingBookingServerRoute: ApiWeddingBookingServerRoute,
  ApiPaymentsCreateCheckoutSessionServerRoute:
    ApiPaymentsCreateCheckoutSessionServerRoute,
  ApiPaymentsStatusServerRoute: ApiPaymentsStatusServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
