/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ModernIndexRouteImport } from './routes/modern/index'
import { Route as ClassicIndexRouteImport } from './routes/classic/index'
import { Route as ServicesToursRouteImport } from './routes/services/tours'
import { Route as ServicesSpecialEventsRouteImport } from './routes/services/special-events'
import { Route as ServicesOneWayRouteImport } from './routes/services/one-way'
import { Route as ServicesExclusiveRouteImport } from './routes/services/exclusive'
import { Route as ServicesBusinessRouteImport } from './routes/services/business'
import { Route as ServicesAirportsRouteImport } from './routes/services/airports'
import { Route as ModernMercedesS500BrabusRouteImport } from './routes/modern/mercedes-s500-brabus'
import { Route as ModernMercedesGls300RouteImport } from './routes/modern/mercedes-gls-300'
import { Route as ModernBentleyMulsanneRouteImport } from './routes/modern/bentley-mulsanne'
import { Route as ClassicRollsRoyceSilverShadowRouteImport } from './routes/classic/rolls-royce-silver-shadow'
import { Route as ClassicRollsRoyceSilverCloudIiRouteImport } from './routes/classic/rolls-royce-silver-cloud-ii'
import { Route as ClassicOldsmobileSuper88RouteImport } from './routes/classic/oldsmobile-super-88'
import { Route as ClassicMercedes280slPagodaRouteImport } from './routes/classic/mercedes-280sl-pagoda'
import { Route as BookingOneWayRouteImport } from './routes/booking/one-way'
import { Route as BookingCorporateRouteImport } from './routes/booking/corporate'
import { Route as BookingIdRouteImport } from './routes/booking/$id'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModernIndexRoute = ModernIndexRouteImport.update({
  id: '/modern/',
  path: '/modern/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassicIndexRoute = ClassicIndexRouteImport.update({
  id: '/classic/',
  path: '/classic/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesToursRoute = ServicesToursRouteImport.update({
  id: '/services/tours',
  path: '/services/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSpecialEventsRoute = ServicesSpecialEventsRouteImport.update({
  id: '/services/special-events',
  path: '/services/special-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesOneWayRoute = ServicesOneWayRouteImport.update({
  id: '/services/one-way',
  path: '/services/one-way',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesExclusiveRoute = ServicesExclusiveRouteImport.update({
  id: '/services/exclusive',
  path: '/services/exclusive',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBusinessRoute = ServicesBusinessRouteImport.update({
  id: '/services/business',
  path: '/services/business',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAirportsRoute = ServicesAirportsRouteImport.update({
  id: '/services/airports',
  path: '/services/airports',
  getParentRoute: () => rootRouteImport,
} as any)
const ModernMercedesS500BrabusRoute =
  ModernMercedesS500BrabusRouteImport.update({
    id: '/modern/mercedes-s500-brabus',
    path: '/modern/mercedes-s500-brabus',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModernMercedesGls300Route = ModernMercedesGls300RouteImport.update({
  id: '/modern/mercedes-gls-300',
  path: '/modern/mercedes-gls-300',
  getParentRoute: () => rootRouteImport,
} as any)
const ModernBentleyMulsanneRoute = ModernBentleyMulsanneRouteImport.update({
  id: '/modern/bentley-mulsanne',
  path: '/modern/bentley-mulsanne',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassicRollsRoyceSilverShadowRoute =
  ClassicRollsRoyceSilverShadowRouteImport.update({
    id: '/classic/rolls-royce-silver-shadow',
    path: '/classic/rolls-royce-silver-shadow',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClassicRollsRoyceSilverCloudIiRoute =
  ClassicRollsRoyceSilverCloudIiRouteImport.update({
    id: '/classic/rolls-royce-silver-cloud-ii',
    path: '/classic/rolls-royce-silver-cloud-ii',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClassicOldsmobileSuper88Route =
  ClassicOldsmobileSuper88RouteImport.update({
    id: '/classic/oldsmobile-super-88',
    path: '/classic/oldsmobile-super-88',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClassicMercedes280slPagodaRoute =
  ClassicMercedes280slPagodaRouteImport.update({
    id: '/classic/mercedes-280sl-pagoda',
    path: '/classic/mercedes-280sl-pagoda',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookingOneWayRoute = BookingOneWayRouteImport.update({
  id: '/booking/one-way',
  path: '/booking/one-way',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingCorporateRoute = BookingCorporateRouteImport.update({
  id: '/booking/corporate',
  path: '/booking/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdRoute = BookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/booking/$id': typeof BookingIdRoute
  '/booking/corporate': typeof BookingCorporateRoute
  '/booking/one-way': typeof BookingOneWayRoute
  '/classic/mercedes-280sl-pagoda': typeof ClassicMercedes280slPagodaRoute
  '/classic/oldsmobile-super-88': typeof ClassicOldsmobileSuper88Route
  '/classic/rolls-royce-silver-cloud-ii': typeof ClassicRollsRoyceSilverCloudIiRoute
  '/classic/rolls-royce-silver-shadow': typeof ClassicRollsRoyceSilverShadowRoute
  '/modern/bentley-mulsanne': typeof ModernBentleyMulsanneRoute
  '/modern/mercedes-gls-300': typeof ModernMercedesGls300Route
  '/modern/mercedes-s500-brabus': typeof ModernMercedesS500BrabusRoute
  '/services/airports': typeof ServicesAirportsRoute
  '/services/business': typeof ServicesBusinessRoute
  '/services/exclusive': typeof ServicesExclusiveRoute
  '/services/one-way': typeof ServicesOneWayRoute
  '/services/special-events': typeof ServicesSpecialEventsRoute
  '/services/tours': typeof ServicesToursRoute
  '/classic': typeof ClassicIndexRoute
  '/modern': typeof ModernIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/booking/$id': typeof BookingIdRoute
  '/booking/corporate': typeof BookingCorporateRoute
  '/booking/one-way': typeof BookingOneWayRoute
  '/classic/mercedes-280sl-pagoda': typeof ClassicMercedes280slPagodaRoute
  '/classic/oldsmobile-super-88': typeof ClassicOldsmobileSuper88Route
  '/classic/rolls-royce-silver-cloud-ii': typeof ClassicRollsRoyceSilverCloudIiRoute
  '/classic/rolls-royce-silver-shadow': typeof ClassicRollsRoyceSilverShadowRoute
  '/modern/bentley-mulsanne': typeof ModernBentleyMulsanneRoute
  '/modern/mercedes-gls-300': typeof ModernMercedesGls300Route
  '/modern/mercedes-s500-brabus': typeof ModernMercedesS500BrabusRoute
  '/services/airports': typeof ServicesAirportsRoute
  '/services/business': typeof ServicesBusinessRoute
  '/services/exclusive': typeof ServicesExclusiveRoute
  '/services/one-way': typeof ServicesOneWayRoute
  '/services/special-events': typeof ServicesSpecialEventsRoute
  '/services/tours': typeof ServicesToursRoute
  '/classic': typeof ClassicIndexRoute
  '/modern': typeof ModernIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/booking/$id': typeof BookingIdRoute
  '/booking/corporate': typeof BookingCorporateRoute
  '/booking/one-way': typeof BookingOneWayRoute
  '/classic/mercedes-280sl-pagoda': typeof ClassicMercedes280slPagodaRoute
  '/classic/oldsmobile-super-88': typeof ClassicOldsmobileSuper88Route
  '/classic/rolls-royce-silver-cloud-ii': typeof ClassicRollsRoyceSilverCloudIiRoute
  '/classic/rolls-royce-silver-shadow': typeof ClassicRollsRoyceSilverShadowRoute
  '/modern/bentley-mulsanne': typeof ModernBentleyMulsanneRoute
  '/modern/mercedes-gls-300': typeof ModernMercedesGls300Route
  '/modern/mercedes-s500-brabus': typeof ModernMercedesS500BrabusRoute
  '/services/airports': typeof ServicesAirportsRoute
  '/services/business': typeof ServicesBusinessRoute
  '/services/exclusive': typeof ServicesExclusiveRoute
  '/services/one-way': typeof ServicesOneWayRoute
  '/services/special-events': typeof ServicesSpecialEventsRoute
  '/services/tours': typeof ServicesToursRoute
  '/classic/': typeof ClassicIndexRoute
  '/modern/': typeof ModernIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/booking/$id'
    | '/booking/corporate'
    | '/booking/one-way'
    | '/classic/mercedes-280sl-pagoda'
    | '/classic/oldsmobile-super-88'
    | '/classic/rolls-royce-silver-cloud-ii'
    | '/classic/rolls-royce-silver-shadow'
    | '/modern/bentley-mulsanne'
    | '/modern/mercedes-gls-300'
    | '/modern/mercedes-s500-brabus'
    | '/services/airports'
    | '/services/business'
    | '/services/exclusive'
    | '/services/one-way'
    | '/services/special-events'
    | '/services/tours'
    | '/classic'
    | '/modern'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/booking/$id'
    | '/booking/corporate'
    | '/booking/one-way'
    | '/classic/mercedes-280sl-pagoda'
    | '/classic/oldsmobile-super-88'
    | '/classic/rolls-royce-silver-cloud-ii'
    | '/classic/rolls-royce-silver-shadow'
    | '/modern/bentley-mulsanne'
    | '/modern/mercedes-gls-300'
    | '/modern/mercedes-s500-brabus'
    | '/services/airports'
    | '/services/business'
    | '/services/exclusive'
    | '/services/one-way'
    | '/services/special-events'
    | '/services/tours'
    | '/classic'
    | '/modern'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/booking/$id'
    | '/booking/corporate'
    | '/booking/one-way'
    | '/classic/mercedes-280sl-pagoda'
    | '/classic/oldsmobile-super-88'
    | '/classic/rolls-royce-silver-cloud-ii'
    | '/classic/rolls-royce-silver-shadow'
    | '/modern/bentley-mulsanne'
    | '/modern/mercedes-gls-300'
    | '/modern/mercedes-s500-brabus'
    | '/services/airports'
    | '/services/business'
    | '/services/exclusive'
    | '/services/one-way'
    | '/services/special-events'
    | '/services/tours'
    | '/classic/'
    | '/modern/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  BookingIdRoute: typeof BookingIdRoute
  BookingCorporateRoute: typeof BookingCorporateRoute
  BookingOneWayRoute: typeof BookingOneWayRoute
  ClassicMercedes280slPagodaRoute: typeof ClassicMercedes280slPagodaRoute
  ClassicOldsmobileSuper88Route: typeof ClassicOldsmobileSuper88Route
  ClassicRollsRoyceSilverCloudIiRoute: typeof ClassicRollsRoyceSilverCloudIiRoute
  ClassicRollsRoyceSilverShadowRoute: typeof ClassicRollsRoyceSilverShadowRoute
  ModernBentleyMulsanneRoute: typeof ModernBentleyMulsanneRoute
  ModernMercedesGls300Route: typeof ModernMercedesGls300Route
  ModernMercedesS500BrabusRoute: typeof ModernMercedesS500BrabusRoute
  ServicesAirportsRoute: typeof ServicesAirportsRoute
  ServicesBusinessRoute: typeof ServicesBusinessRoute
  ServicesExclusiveRoute: typeof ServicesExclusiveRoute
  ServicesOneWayRoute: typeof ServicesOneWayRoute
  ServicesSpecialEventsRoute: typeof ServicesSpecialEventsRoute
  ServicesToursRoute: typeof ServicesToursRoute
  ClassicIndexRoute: typeof ClassicIndexRoute
  ModernIndexRoute: typeof ModernIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modern/': {
      id: '/modern/'
      path: '/modern'
      fullPath: '/modern'
      preLoaderRoute: typeof ModernIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic/': {
      id: '/classic/'
      path: '/classic'
      fullPath: '/classic'
      preLoaderRoute: typeof ClassicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/tours': {
      id: '/services/tours'
      path: '/services/tours'
      fullPath: '/services/tours'
      preLoaderRoute: typeof ServicesToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/special-events': {
      id: '/services/special-events'
      path: '/services/special-events'
      fullPath: '/services/special-events'
      preLoaderRoute: typeof ServicesSpecialEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/one-way': {
      id: '/services/one-way'
      path: '/services/one-way'
      fullPath: '/services/one-way'
      preLoaderRoute: typeof ServicesOneWayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/exclusive': {
      id: '/services/exclusive'
      path: '/services/exclusive'
      fullPath: '/services/exclusive'
      preLoaderRoute: typeof ServicesExclusiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/business': {
      id: '/services/business'
      path: '/services/business'
      fullPath: '/services/business'
      preLoaderRoute: typeof ServicesBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/airports': {
      id: '/services/airports'
      path: '/services/airports'
      fullPath: '/services/airports'
      preLoaderRoute: typeof ServicesAirportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modern/mercedes-s500-brabus': {
      id: '/modern/mercedes-s500-brabus'
      path: '/modern/mercedes-s500-brabus'
      fullPath: '/modern/mercedes-s500-brabus'
      preLoaderRoute: typeof ModernMercedesS500BrabusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modern/mercedes-gls-300': {
      id: '/modern/mercedes-gls-300'
      path: '/modern/mercedes-gls-300'
      fullPath: '/modern/mercedes-gls-300'
      preLoaderRoute: typeof ModernMercedesGls300RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modern/bentley-mulsanne': {
      id: '/modern/bentley-mulsanne'
      path: '/modern/bentley-mulsanne'
      fullPath: '/modern/bentley-mulsanne'
      preLoaderRoute: typeof ModernBentleyMulsanneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic/rolls-royce-silver-shadow': {
      id: '/classic/rolls-royce-silver-shadow'
      path: '/classic/rolls-royce-silver-shadow'
      fullPath: '/classic/rolls-royce-silver-shadow'
      preLoaderRoute: typeof ClassicRollsRoyceSilverShadowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic/rolls-royce-silver-cloud-ii': {
      id: '/classic/rolls-royce-silver-cloud-ii'
      path: '/classic/rolls-royce-silver-cloud-ii'
      fullPath: '/classic/rolls-royce-silver-cloud-ii'
      preLoaderRoute: typeof ClassicRollsRoyceSilverCloudIiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic/oldsmobile-super-88': {
      id: '/classic/oldsmobile-super-88'
      path: '/classic/oldsmobile-super-88'
      fullPath: '/classic/oldsmobile-super-88'
      preLoaderRoute: typeof ClassicOldsmobileSuper88RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic/mercedes-280sl-pagoda': {
      id: '/classic/mercedes-280sl-pagoda'
      path: '/classic/mercedes-280sl-pagoda'
      fullPath: '/classic/mercedes-280sl-pagoda'
      preLoaderRoute: typeof ClassicMercedes280slPagodaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/one-way': {
      id: '/booking/one-way'
      path: '/booking/one-way'
      fullPath: '/booking/one-way'
      preLoaderRoute: typeof BookingOneWayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/corporate': {
      id: '/booking/corporate'
      path: '/booking/corporate'
      fullPath: '/booking/corporate'
      preLoaderRoute: typeof BookingCorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id': {
      id: '/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof BookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  BookingIdRoute: BookingIdRoute,
  BookingCorporateRoute: BookingCorporateRoute,
  BookingOneWayRoute: BookingOneWayRoute,
  ClassicMercedes280slPagodaRoute: ClassicMercedes280slPagodaRoute,
  ClassicOldsmobileSuper88Route: ClassicOldsmobileSuper88Route,
  ClassicRollsRoyceSilverCloudIiRoute: ClassicRollsRoyceSilverCloudIiRoute,
  ClassicRollsRoyceSilverShadowRoute: ClassicRollsRoyceSilverShadowRoute,
  ModernBentleyMulsanneRoute: ModernBentleyMulsanneRoute,
  ModernMercedesGls300Route: ModernMercedesGls300Route,
  ModernMercedesS500BrabusRoute: ModernMercedesS500BrabusRoute,
  ServicesAirportsRoute: ServicesAirportsRoute,
  ServicesBusinessRoute: ServicesBusinessRoute,
  ServicesExclusiveRoute: ServicesExclusiveRoute,
  ServicesOneWayRoute: ServicesOneWayRoute,
  ServicesSpecialEventsRoute: ServicesSpecialEventsRoute,
  ServicesToursRoute: ServicesToursRoute,
  ClassicIndexRoute: ClassicIndexRoute,
  ModernIndexRoute: ModernIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
